# Generated by Django 5.1.6 on 2025-02-09 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='events',
            field=models.ManyToManyField(related_name='participants', to='events.event'),
        ),
    ]
