# Generated by Django 5.1.6 on 2025-02-10 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_participant_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(choices=[('DHAKA', 'Dhaka'), ('CHITTAGONG', 'Chittagong'), ('KHULNA', 'Khulna'), ('RAJSHAHI', 'Rajshahi'), ('BARISAL', 'Barisal'), ('SYLHET', 'Sylhet'), ('RANGPUR', 'Rangpur'), ('MYMENSINGH', 'Mymensingh')], max_length=100),
        ),
    ]
