# Generated by Django 5.1.6 on 2025-03-15 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='rsvps',
            new_name='user_event',
        ),
    ]
