# Generated by Django 5.1.6 on 2025-03-13 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_remove_event_rsvps_event_participate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='participate',
            new_name='user',
        ),
    ]
