# Generated by Django 5.1.6 on 2025-03-16 18:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_rsvp_unique_user_event_rsvp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='rsvp',
            name='unique_user_event_rsvp',
        ),
        migrations.AddConstraint(
            model_name='rsvp',
            constraint=models.UniqueConstraint(fields=('user', 'event', 'response_type'), name='unique_user_event_response'),
        ),
    ]
