# Generated by Django 5.1.6 on 2025-03-13 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_remove_event_user_event_image_event_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, default='upload/default.jpg', null=True, upload_to='upload/'),
        ),
    ]
