# Generated by Django 5.1.6 on 2025-03-14 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_alter_event_participants_eventrsvp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventrsvp',
            name='attending',
            field=models.BooleanField(default=False),
        ),
    ]
